### ISSUE TITLE
Port 80 und 443: Permission denied

### ISSUE THREAD

**Issue by Gogo74** [christianTF/LoxBerry-Plugin-TCP2UDP#1]
Hallo,

ich habe einen VegeHub um die Feuchte im Boden zu übertragen. Dieser kann leider nur auf Port 80 oder 443 senden. Bei beiden Ports bekomme ich einen Fehler:
12:23:12 ERROR: Could not create tcp socket for port 443: Permission denied
Kann ich dies durch Konfiguration beheben?

Danke.

**Comment by christianTF** [comment]
Dein VegeHub ist HTTP nicht TCP.
Du müsstest den - offenbar mit Authentifizierung - direkt mit einem virtuellen HTTP-Eingang (Port 80) vom Miniserver abfragen können (hab mich jetzt aber nicht eingehend damit beschäftigt).
TCP2UDP macht *reine* TCP-Kommunikation.

**Comment by Gogo74** [comment]
Sorry. Danke. Anfängerfehler.
Kennst du eine Möglichkeit wie ich die Daten in den MiniServer bekomme?
Leider kann ich meinen VegeHub nicht abfragen, sondern er kann nur schicken (JSON über http über Port 80 oder 443).
Über eine Cloud gäbe es Möglichkeiten, aber ich bin kein Freund davon.

**Comment by christianTF** [comment]
Über 80/443 kann man nichts "schicken", da kann ein Server nur abholen. Wo ist den die Beschreibung des Protokolls?

**Comment by Gogo74** [comment]
Server einrichten:
https://www.vegetronix.com/Products/VG-HUB/QuickStart.phtml

Protokoll:
http://vegecloud.com/Documentation/UpdateApi.phtml

Ich werde mal meinen Netzwerkverkehr untersuchen, um zu sehen auf welchen Port das Paket verschickt wird. 80 und 443 waren meine Vermutungen. Vielleicht liege ich hier falsch.

**Comment by christianTF** [comment]
Aus den Screenshots sieht man nur, dass die Box an verschiedene Clouddienste versenden kann.
Da aus der spärlichen Dokumentation sonst nichts hervorgeht, kann ich dir leider nicht weiterhelfen. 
Wenn ich mich nicht getäuscht habe, ist das Projekt offenbar auch nicht fertiggestellt worden (bin über eine Webseite gestolpert, dass das Kickstarter-Projekt eingestellt ist).

Gibt es eine Webseite, die die Werte anzeigt? 
Die könntest du vom MS aus abrufen, und entsprechende Befehlserkennungen erstellen. Die Authentifizierung nicht vergessen. 
Wenn du nicht weiter weißt, mach am besten einen Thread im loxforum.

lg, Christian
